[package]
name = "http-sv"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
nom = "8.0.0"
thiserror = "2.0.12"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [] }
